endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

server:
  port: 8765

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /mars
  routes:
    account:
      path: /account/**
      serviceId: account-service
      sensitive-headers:
    expenses:
      path: /expenses/**
      serviceId: expenses-service
      sensitive-headers:
    dlearnservice:
      path: /dlearn/**
      serviceId: deeplearnsidecar-service
      sensitive-headers: